# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b96f426548b17c97dac8a6a2daa574f80d753afd588d2f339acf2f9501101403b3b0538bc55a93cdc0b1928aa6bbbfafd6cc61fe0a0763f8ec312cf683e8146b

test:
  secret_key_base: d571014bbe0cef187ef9cf6f604af27f8c31509b449f7bf7ec76d1ed304858e36017751378d289ff2f6b4e67209635e8d69787efd19f3f5fd880d85b93c3e7fc

# Do not keep production secrets in the repository,
# instead read values from the environment.

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
